# Indexing, Slicing and Iteration

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(24)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
arr1 = np.arange(24).reshape(6, 4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
arr1[1,1]

np.int64(5)

In [6]:
arr1[5,2]

np.int64(22)

In [7]:
arr1[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [10]:
arr1[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [13]:
arr1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [18]:
arr1[4:,2:]

array([[18, 19],
       [22, 23]])

In [19]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [21]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
