# Numpy Operations

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [3]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

## vector multiplication

In [4]:
arr1 * arr2

array([ 4, 10, 18, 28, 40, 54])

## vector to scalar

In [5]:
arr1 > 4

array([False, False, False, False,  True,  True])

In [6]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6, 12).reshape(3,2)

In [7]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [9]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [10]:
arr4.max()

np.int64(11)

In [11]:
arr4.min()

np.int64(6)

In [12]:
arr4.min(axis=0)

array([6, 7])

In [13]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [14]:
arr4.mean(axis=1)

array([ 6.5,  8.5, 10.5])

In [15]:
arr4.mean(axis=0)

array([8., 9.])

In [16]:
arr4.std(axis=1)

array([0.5, 0.5, 0.5])

In [17]:
np.median(arr4)

np.float64(8.5)