# Indexing with Boolean Arrays

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr1

array([[40, 83, 40,  8, 84],
       [76,  8, 26, 85, 36],
       [66,  3, 40, 98, 73],
       [57, 73, 76, 11, 47]], dtype=int32)

In [3]:
arr1[1]

array([76,  8, 26, 85, 36], dtype=int32)

In [4]:
arr1[0][2]

np.int32(40)

## Indexing using boolean array

In [5]:
arr1[arr1>50]

array([83, 84, 76, 85, 66, 98, 73, 57, 73, 76], dtype=int32)

In [7]:
arr1[(arr1 > 50) & (arr1 % 2 != 0)]

array([83, 85, 73, 57, 73], dtype=int32)